### ISSUE TITLE
Camera selector overflows on small display sizes

### ISSUE THREAD

**Issue by HexaCubist** [Fallstop/modern-svelte-qr-scanner#1]
![image](https://user-images.githubusercontent.com/8563277/144913952-7c844d80-aa4a-43f8-8b9a-a29673a365b1.png)

## What happens?

The dropdown for camera selection falls outside the bounds of the view when the height is not large enough to contain all options. Because ".video-container" has overflow disabled, the rest of the options are hidden

## What should happen?

The dropdown should expand outside the bounds of the container, or the dropdown should scroll if it is too long.

**Comment by Fallstop** [comment]
Fixed in [v1.2.8](https://github.com/Fallstop/modern-svelte-qr-scanner/releases/tag/1.2.8). It now goes into a more compact mode when the container is less than 400px.

This means that the camera list should scroll before it is obscured by the clipping required to force the video preview to a aspect ratio.
![image](https://user-images.githubusercontent.com/43323210/150700145-96c1f568-3e1b-42ca-a081-d6d58e0fc0ea.png)
